apiVersion: v1
kind: ConfigMap
metadata:
  name: application-module
  namespace: statefun
  labels:
    app: statefun
data:
  module.yaml: |+
    kind: io.statefun.endpoints.v2/http
    spec:
      functions: com.medidata.graphql/*
      urlPathTemplate: https://graphql.imedidata.com/{function.name}