apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-forms-resolver
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: docker.io/isterin/knative-forms-resolver
        env:
        - name: TARGET
          value: "Node.js Sample v1"
